
class Report:

    X_AXIS_START_POINT = 50
    X_AXIS_COLUMN2 = 320

    Y_AXIS_INITIAL_LENGTH = 650
    Y_AXIS_INITIAL_DIFFERENCE = 20

    HEADER_FONT_SIZE = 18
    BODY_FONT_SIZE = 12
    FOOTER_FONT_SIZE = 10
